### ISSUE TITLE
Scheme configurations

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#106]
Being able to specify schemes in `2.0.0` is great, but I see a few issues:
- there is no way to choose the build configuration other than in test. The rest just use `debug`
- The options under a target about enabling build types doesn't seem to have affect. They are all always ticked in the Build tab except `Test` no matter what options you provide. The default for these should probably be to just enable them all, and then optionally disable them with eg. `profiling_enabled: false`
- if schemes are defined for a target, maybe the default scheme for that target shouldn't be generated
- the default scheme that is generated if you don't specify any always uses the same configuration for run, test, profile, analyze, and archive (seems to just be the first config it finds)

---

For what it's worth my use case is to have the following build configurations:
- test debug
- test release
- staging debug
- staging release
- production debug
- production release

I then want to create `iOS Test`, `iOS Staging` and `iOS Production` schemes that use the relevant debug configuration for `run`, `test` and `analyze`, and the relevant release configuration for `profile` and `archive`
So example the `iOS Staging` scheme would have the following build configurations for each build type:
```
run:
  build_configuration: staging debug
test:
  build_configuration: staging debug
profile:
  build_configuration: staging release
analyze:
  build_configuration: staging debug
archive:
  build_configuration: staging release

```
