### ISSUE TITLE
Generate options

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#117]
It would be useful to pass an optional path to a spec, and also an optional project name when generating:
 ```
struct generate --spec myProject.yml --project MyProject
```
If no spec path is passed it uses the default `project.yml`. If no project is passed it uses the name of the spec file

**Comment by lyptt** [comment]
Hi @yonaskolb, struct always looks for common names for the project files, for YAML/JSON it's `project.{yaml|yml|json}` and for Specfiles it's `Specfile`. This is mainly around consistency more than anything, and follows similar conventions to Fastlane's Fastfile, Cocoapod's Podfile, etc.

Project names can be changed by using variants - each variant name will be the name of the project, and you can disable the standard `project.xcodeproj` output. The following example should work:

```
variants:
  # $base is your standard project.xcodeproj
  $base:
    abstract: true
  MyProject:
```
