### ISSUE TITLE
Target configuration and configurations

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#118]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

[2.1.1]

## Spec version

[2.1.1]

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

When specifying a target it's not possible to have both `configuration` and `configurations`.
Both should be able to be set for the same target.

## Reproduction steps
```
iOS:
    sources: iOS
    platform: ios
    type: ":application"
    configuration:
      INFOPLIST_FILE: iOS/Info.plist
    configurations:
      debug: iOS/configurations/test_debug_iOS.xcconfig
      staging debug: iOS/configurations/staging_debug_iOS.xcconfig
      production debug: iOS/configurations/production_debug_iOS.xcconfig
      test release: iOS/configurations/test_release_iOS.xcconfig
      staging release: iOS/configurations/staging_release_iOS.xcconfig
      production release: iOS/configurations/production_release_iOS.xcconfig
    references:
```
## Expected result

Target gets `INFOPLIST_FILE`  set and also has project configurations set

## Actual result

Only the project configurations are set. If the `configurations` is removed, `INFOPLIST_FILE` gets set correctly

**Comment by lyptt** [comment]
Hi @yonaskolb, that's correct, if you're using xcconfig references, you need to specify your INFOPLIST_FILE inside the xcconfig file. Currently, you can either use xcconfig references, or overrides, but not both.

This is currently described in the [documentation](https://github.com/workshop/struct/wiki/Spec-format%3A-v2.0#target-configuration):

> Please note that when specifying xcconfig references, any overrides are ignored.

**Comment by yonaskolb** [comment]
Yes, but xcode configuration references are set on a project level. While specific `overrides` are set on a target. There should be no reason to not allow both of them right?

**Comment by yonaskolb** [comment]
If it's just limited to xcodeconfig files, then variants lose a lot of their power as you can't set specific build settings on them while still having fallback project configurations

**Comment by lyptt** [comment]
In struct, you can set configuration references on a project level, and an individual target level. From the above example you've posted, it appears you're setting them on a target level. If you wish to achieve the behaviour you describe, you can do as follows:

```yaml
configurations:
  debug:
    source: iOS/configurations/test_debug_iOS.xcconfig
  staging debug:
    type: debug
    source: iOS/configurations/staging_debug_iOS.xcconfig
  production debug:
    type: debug
    source: iOS/configurations/production_debug_iOS.xcconfig
  release:
    source: iOS/configurations/test_release_iOS.xcconfig
  staging release:
    type: release
    source: iOS/configurations/staging_release_iOS.xcconfig
  production release:
    type: release
    source: iOS/configurations/production_release_iOS.xcconfig
targets:
  iOS:
    configuration:
      INFOPLIST_FILE: iOS/Info.plist
```

**Comment by yonaskolb** [comment]
Well I actually have different targets that all point to different xcode config files

**Comment by lyptt** [comment]
In this scenario, your individual targets' xcconfig files would need to specify the INFOPLIST_FILE within them. Currently Struct does not support combining xcconfig references with configuration overrides.

**Comment by yonaskolb** [comment]
It wouldn't need to combine xcconfig references.
Whenever a target has a xcconfig file set for a special project configuration, those build settings sit above a target's build settings. All I'm asking for is to change a target's build settings while also still referencing an xcodeconfig file for the project config. Then the target has these levels of build settings viewable in Xcode as level:
`Target`, `Config File`, `Project`, `Platform Default`

**Comment by lyptt** [comment]
Yes, I believe we're talking about the same thing. Currently Struct does not support specifying build settings in addition to an xcconfig file. I'll mark this as a feature request for 2.2.0.

**Comment by yonaskolb** [comment]
Ok cool. Is it just a case of removing a check that limits it to one? Because both features work independently at the moment, just not together.

**Comment by lyptt** [comment]
The `configurations` and `configuration` block behaviour would need to remain the same. `configuration` is shorthand for specifying a full `configurations` block when all of your configuration settings are identical. This is why you can only specify one or the other. 

Behind the scenes when specifying a `configuration` block, Struct will generate a target configuration entry based on that block for every build configuration in your project.

In your particular use case, we would need to add support for specifying a more detailed variant of the `configurations` block, for example, something like this:

```yaml
    configurations:
      debug:
        source: iOS/configurations/test_debug_iOS.xcconfig
        overrides:
          INFOPLIST_FILE: iOS/Info.plist
```

**Comment by yonaskolb** [comment]
Ok got it. If adding that extra functionality to configurations then it would be good to have some way of specifying a build setting once if it's the same for each configuration. Maybe a `$base` config?

**Comment by lyptt** [comment]
Hi @yonaskolb, we actually added this to 2.0.0, but it hasn't been documented yet. You can use it like this:

```yaml
targets:
  my-target:
    configurations:
      $base:
        IPHONEOS_DEPLOYMENT_TARGET: 10.2
      debug:
        INFOPLIST_FILE: Info.plist
      release:
        INFOPLIST_FILE: Info-Release.plist
```

**Comment by lyptt** [comment]
This may actually solve your issue in the short term too, I don't believe we restrict adding build settings from $base to configurations using xcconfig references. If my theory is correct, you should be able to do something like this:

```yaml
targets:
  my-target:
    configurations:
      $base:
        IPHONEOS_DEPLOYMENT_TARGET: 10.2
      debug: path/to/config.xcconfig
      release: path/to/config.xcconfig
```
