### ISSUE TITLE
Target references not working (Add support for linking to framework targets within the same project)

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#122]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

[2.1.0]

## Spec version

[2.1.0]

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

Trying to add a target as a reference to another

## Reproduction steps
```
targets:
  iOS:
    sources: iOS
    platform: ios
    type: ":application"
    references:
      - SDK_iOS
  SDK_iOS:
    sources: SDK_iOS
    platform: ios
    type: ":framework"
```

## Expected result

The` iOS` target would reference framework `SDK_iOS`

## Actual result

No referencing occurs

**Comment by lyptt** [comment]
I believe this was an oversight when adding target reference support. Ideally we should support the use case of linking to framework targets within the same project. 

I've done a quick proof of concept that works, however there are complications around adding support for this and having it link and embed a framework automatically, as there are multiple kinds of framework, and only one kind can be embedded into an application bundle.

Instead we should allow for being able to reference a target as a build dependency (which is the existing behaviour), and also referencing a target as a linked framework, allowing for all of the same settings that other references benefit from.

In order to support this properly we'd need to define a new variant of a target reference within the YAML/JSON format:

```yaml
   - target: SDK_iOS
     copy: false
     codeSignOnCopy: false
```

The key `target` would indicate that this is still a `::TargetReference`, and the relevant settings would be passed on to configure how the framework is processed at build time.
