### ISSUE TITLE
How to link to Carthage dependancies

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#124]
I'm trying to add references to Carthage dependancies like this
```
references:
  - location: Carthage/Build/iOS/Alamofire.framework
```
But the target doesn't build saying `No such module 'Alamofire'`. Is there more configuration required to get this working?

**Comment by lyptt** [comment]
Hi @yonaskolb, that is correct syntax yes, but make sure to also declare your FRAMEWORK_SEARCH_PATHS. You need to include the directory containing your Carthage frameworks in order for Xcode to resolve them (annoyingly).

For example, in your case, you could do something like this:

```yaml
references:
  - location: Carthage/Build/iOS/Alamofire.framework
configurations:
  $base:
    FRAMEWORK_SEARCH_PATHS:
    - $(inherited)
    - Carthage/Build/iOS
```

Ideally we should auto-inject the directories into your settings (this has literally just sprung to mind now), but for the time being, that will work for you.

You can also have Struct auto-link to any frameworks it finds in a directory, to save you adding each reference individually:

```yaml
sources:
  my-source-dir
  Carthage/Build/iOS
```

**Comment by yonaskolb** [comment]
I can get it building now, but at runtime I get this error:
```
dyld: Library not loaded: @rpath/Result.framework/Result
  Referenced from: /Users/Yonas/Library/Developer/CoreSimulator/Devices/4610CC5E-0AC7-4674-AEB1-2DF607BCABE6/data/Containers/Bundle/Application/5CD28B30-7DC4-441E-9428-9F2D489DCAB6/Axis_iOS.app/Axis_iOS
  Reason: image not found
```
This is how the target references are specifed:
```
    configuration:
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - $(PROJECT_DIR)/Carthage/Build/iOS
    references:
      - location: Carthage/Build/iOS/BrightFutures.framework
      - location: Carthage/Build/iOS/Result.framework
```

Is there something else required?

**Comment by lyptt** [comment]
Hi @yonaskolb, nearly there!

I think the final thing you need to do is specify that the references should be copied and code signed, if you skip doing this the frameworks will not be embedded into your application. This is due to the fact that a lot of frameworks do not support being embedded (fake frameworks, etc), and only support being linked. To err on the side of caution, this is opt-in when specifying frameworks individually.

So for your above example, try this:

```yaml
    references:
      - location: Carthage/Build/iOS/BrightFutures.framework
         copy: true
         codeSignOnCopy: True
```
