### ISSUE TITLE
Add support for cross-platform targets

### ISSUE THREAD

**Issue by lyptt** [workshop/struct#134]
Currently a target can only be associated with one platform, however a common use case is to have multiple targets per-platform from a single source set to enable that target to be consumed on multiple platforms.

This feature would enable a target to specify multiple platforms, as follows:

**YAML/JSON**
```yaml
targets:
  My framework:
    platform:
    - ios
    - tv
```

**Specfile**
```ruby
target 'My framework' do
  platform 'ios'
  platform 'tv'
end
```

This would perform a few actions within struct:

- For each platform, a target suffixed by the platform name would be generated:
  - My framework-iOS
  - My framework-tvOS
- Each target would define the preprocessor variable PLATFORM_{PLATFORM_NAME}
- Each target variant would share the same source set, the source set group will retain the original target's name

**Todo:**
- [x] Parsing for platform-scoped configurations
- [x] Parsing for platform-scoped references
- [x] Parsing for platform-scoped variant configurations
- [x] Parsing for platform-scoped variant references
- [x] Parsing for platform-scoped i18n-resources
- [x] Parsing for platform-scoped variant i18n-resources
- [x] Parsing for more than one platform
- [x] Preprocessing to resolve platform-scoped targets into multiple targets

**Comment by yonaskolb** [comment]
Great solution! Much better than currently defining duplicate targets with differing platforms. One wrinkle though would be how to reference Carthage dependancies as they are build per platform `- location: Carthage/Build/tvOS/BrightFutures.framework`. Another problem would be if that cross platform "target" referenced another cross platform "target". Struct would need to intelligently get it to reference the correct actual target.
Once possible solution is to have some sort of `platformTargets` list that acts a bit like a variant where you can specify overrides per platform that get used in the actually created target.

**Comment by lyptt** [comment]
Hi @yonaskolb, yes we'll have to come up with a mechanism to only link to a specific platform's frameworks. Potentially we could namespace the references when using multiple platforms, for example:

```yaml
targets:
  My framework:
    platform:
    - ios
    - tv
    references:
      ios:
      - location: Carthage/Build/iOS/BrightFutures.framework
      tv
      - location: Carthage/Build/tvOS/BrightFutures.framework
```
