### ISSUE TITLE
Cross platform product name issue

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#144]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

[2.2.0]

## Spec version

[2.2.0]

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

When defining multiple targets for a cross platform framework, a common `PRODUCT_NAME` is used, so that importing of the framework doesn't need to specify the specific target ie `import MyFramework` instead of `import MyFramework-ios`. This is especially important in cross platform frameworks which import other cross platform frameworks.
When `PRODUCT_NAME` is specified however, target framework linking breaks

## Reproduction steps

Given the following spec
```
version: 2.2.0
configurations:
  debug:
    type: debug
  release:
    type: release
targets:
  MyApp:
    sources: AppSource
    platform: ios
    type: ":application"
    references:
      - target: MyFramework_iOS
        copy: true
        codeSignOnCopy: true
  MyFramework_iOS:
    sources: FrameworkSource
    platform: ios
    type: ":framework"
    configuration:
      PRODUCT_NAME: MyFramework
  MyFramework_tvOS:
    sources: FrameworkSource
    platform: tv
    type: ":framework"
    configuration:
      PRODUCT_NAME: MyFramework

```

## Expected result

`MyApp` target correctly links to `MyFramework_iOS` and builds

## Actual result

`MyApp` generates a broken framework linkage and encounters a linker error: 
```
...
ld: framework not found MyFramework_iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by lyptt** [comment]
Hi @yonaskolb, thanks for filing this issue. I've released 2.2.1 which allows target names to be overridden by the PRODUCT_NAME setting just like Xcode does. This change can be taken advantage of regardless of spec version.

You will need to change your reference to not have the '_iOS' suffix, like so:

```yaml
version: 2.2.0
configurations:
  debug:
    type: debug
  release:
    type: release
targets:
  MyApp:
    sources: App
    platform: ios
    type: ":application"
    references:
      - target: MyFramework
        copy: true
        codeSignOnCopy: true
  MyFramework_iOS:
    sources: FrameworkExample
    platform: ios
    type: ":framework"
    configuration:
      PRODUCT_NAME: MyFramework
  MyFramework_tvOS:
    sources: FrameworkExample
    platform: tv
    type: ":framework"
    configuration:
      PRODUCT_NAME: MyFramework
```
