### ISSUE TITLE
Add a means for reducing duplication for build configuration

### ISSUE THREAD

**Issue by lyptt** [workshop/struct#55]
Currently in struct, the same configuration settings tend to be redeclared when defining each build configuration manually, for example:

```yaml
targets:
  My app:
    configurations:
      debug:
        overrides:
          IPHONEOS_DEPLOYMENT_TARGET: '9.1'
          INFOPLIST_FILE: Info.plist
      release:
        overrides:
          IPHONEOS_DEPLOYMENT_TARGET: '9.1'
          INFOPLIST_FILE: Info.plist
```

Ideally, we'd be able to declare this once for a target configuration, and then be able to inherit this for other configurations.

**Comment by jcampbell05** [comment]
You can see how this was done in Xcake here https://github.com/maximkhatskevich/MKHRequirement/blob/develop/Cakefile

An overview of how it worked in Xcake:
- A user could configure the configurations of the project, the target would then inherit these if it has a `$(inherited)` setting
- Xcake allowed users to set all configurations in a particular node (Project or Target) by iterating through them all, but earlier versions of xcake had a "all" configuration that would set all of the build settings for all configurations unless overrided. The first one works better in a DSL but the second may make sense for a Yaml or JSON File.
- Users can use variables to share settings globally, This is because of Xcake's DSL really just being Ruby so will work for Struct's DSL. We could add a environment section to the DSL for this as well though so Yaml and JSON could have this. That way you could have something like this

```
envs:
   swift_version: 3.0
target:
   some_setting: $swift_version
```

One advantage could be allow these environmental variables to be passed in to struct, so $swift_version could be passed in by fastlane which would be cool but probably overkill ;)

**Comment by lyptt** [comment]
Yeah @jcampbell05 I was considering variables for YAML and JSON too! [Packer](https://www.packer.io/) has a very similar approach to this, and it even supports overriding variables on the command line when invoking the tool, which would be very awesome to include.

I like the idea of going with $(inherited), or some similar mechanism to 'inherit' configurations from another build configuration. It fits in perfectly with struct's approach to implicit sensible default behaviours for project generation 👍

**Comment by jcampbell05** [comment]
> Yeah @jcampbell05 I was considering variables for YAML and JSON too! Packer has a very similar approach to this, and it even supports overriding variables on the command line when invoking the tool, which would be very awesome to include.

It would fit in well with Fastlane usage as well :) 

> 
> I like the idea of going with $(inherited), or some similar mechanism to 'inherit' configurations from another build configuration. It fits in perfectly with struct's approach to implicit sensible default behaviours for project generation

Cool so I guess we allow user to specify project level configurations (if we don't already).

Do we also allow a user to declare settings on configurations via a special `all` configuration in JSON and YAML. In the DSL the users can simply iterate through all configurations and set a setting ? I would imagine there may be cases that a setting may be target specific but needed to be applied across all configurations

**Comment by lyptt** [comment]
We do have an alternate declaration style, but if you need to adjust anything between Debug / Release you can't use it, as it applies the same overrides for every configuration:

```yaml
target:
   My app:
     configuration:
       SWIFT_VERSION: '3.0'
```
