### ISSUE TITLE
Add a hook system to Struct

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#64]
From https://github.com/jcampbell05/xcake/issues/124.

Allow for things like triggering command after project is generated like `pod install` (Already in Xcake) and allow people to modify generated project through Xcodeproj for extra control.

**Comment by lyptt** [comment]
It'd be interesting to see if we can achieve this for both YAML/JSON and DSL formats. For example something like this:

```yaml
scripts:
  pre-generate: scripts/pod_install.sh
  post-generate: scripts/update_targets.rb
  post-install: scripts/update_project.rb
```

```ruby
spec '1.2.0' do
  pre_generate do
    `pod install`
  end
  post_generate do
    spec.targets.each { |target| target.name = target.name.downcase }
  end
  post_install do
    project.build_configurations.each { |config| puts config  }
  end
end
```
